### PR TITLE
Adding fixes required for standalone HOMME

### PR DESCRIPTION
**Pull request by jayeshkrishna**
Adding fixes that are required to build standalone HOMME with
Scorpio

* Adding pio_copy_att()
* Some minor change to build system to disable duplicate (with
  HOMME) targets

### CODE REVIEW

**Comment by jayeshkrishna** [comment]
Note that the code to support copying variables needs to be moved to C and re-implemented. Since HOMME needs this feature this PR adds it, for now, with minimal changes from Scorpio classic.

**Comment by dqwu** [comment]
@jayeshkrishna 
PIO_ENABLE_TESTS might needs to be reverted to ON in this PR.

**Comment by jayeshkrishna** [comment]
I turned it off because HOMME has target (cmake) conflicts with the tests target. This can be re-enabled once we fix the HOMME standalone build system to incorporate Scorpio the "right" way.

**Comment by dqwu** [comment]
@jayeshkrishna 
We might need to look at a new test failed in Valgrind mode:
https://my.cdash.org/testDetails.php?test=53687577&build=1763830

**Comment by jayeshkrishna** [comment]
The warning about the "-1" file descriptor looks like its from MPI_File_open() mentioned here : https://github.com/pmodels/mpich/issues/2894

However I can reproduce the failure in the test log. Still debugging

**Comment by jayeshkrishna** [comment]
Looks like the latest build was successful. Must be a synchronization issue with the file system (since the test deletes a file and recreates it multiple times)

**Pull request merged**
