### PR TITLE
Updating version and docs for v1.6.5

### PR DESCRIPTION
**Pull request by jayeshkrishna**
Updating version from 1.6.4 to 1.6.5 . Also adding generated docs.

SCORPIO v1.6.5 includes,

* Fix to support CDF5 file format when PnetCDF is not available

### CODE REVIEW

**Comment by jayeshkrishna** [comment]
Skipping review since we are just updating version number and adding generated docs

**Comment by rljacob** [comment]
How do you guys make your docs?   And how is it displayed from the docs dir in scorpio?

**Comment by jayeshkrishna** [comment]
The docs are generated using doxygen (from comments in the source code). Currently we just have it in the source tree (html pages) but we need to make it available to users.

**Comment by rljacob** [comment]
Try using this:  https://github.com/marketplace/actions/doxygen-github-pages-deploy-action

**Pull request merged**
