### PR TITLE
Exclude MPI C++ headers

### PR DESCRIPTION
**Pull request by jayeshkrishna**
Handle errors due to including MPI headers in C++ source files.
Also removing source code hacks required for including MPI
header files in C++ sources.

### CODE REVIEW

**Comment by jayeshkrishna** [comment]
@tkurc : Can you check if the ADIOS builds that required the source code hack (include mpi.h directly from the C++ source) work on this branch?
I have tried building the code with MPICH and OpenMPI on anlworkstation and it builds successfully.

**Comment by jayeshkrishna** [comment]
@tkurc : Any thoughts on this PR?

**Comment by dqwu** [comment]
@jayeshkrishna 
Looks good to me. Also, this PR needs to be rebased after adios2_integration PR is merged to master.

**Comment by jayeshkrishna** [comment]
Is there any specific reason the rebase is required?

**Comment by jayeshkrishna** [comment]
@dqwu pointed out that some of the preprocessor macros have been changed in https://github.com/E3SM-Project/scorpio/pull/283 and some code removed in this PR uses these macros (Although this PR does not have conflicts with the current master, merging PR #283 to master will result in conflicts with this branch).
So will wait until PR #283 is merged to master to rebase this branch.

**Pull request merged**
