### PR TITLE
Put user-provided paths first in the list of search dirs in LibFind

### LINKED ISSUE #396: User provided paths do not override system paths when searching for libraries
@bartgol reported,
```
When the user provides a ${PKG_NAME}_PATHS variable, it should be put at the 
beginning of the search path (in LibFind.cmake), to avoid looking for system libs first.

Without this mod, on my machine scorpio picked up the system netcdf (which is not parallel).
 After this mod, my user provided path is honored, and the correct netcdf installation is picked up.
```

### PR DESCRIPTION
**Pull request by bartgol**
Add user provided `${PKG_NAME}_PATHS` to the beginning of the
search directories, to avoid looking for the system libraries first.

Without this modification libraries in the user specified paths would
be ignored if the libraries are already present in the system paths.

Fixes #396

### CODE REVIEW

**Comment by bartgol** [comment]
@jayeshkrishna Does this PR look reasonable?

**Comment by jayeshkrishna** [comment]
Looks fine to me, @dqwu please take a look at the PR

**Comment by jayeshkrishna** [comment]
@bartgol : I have modified the PR description and included your old PR description in a separate issue (the PR description is used as the content of the PR merge commit message). Please feel free to modify it if needed.

**Review by dqwu — APPROVED** [review]
Looks good to me, thanks.

**Pull request merged**
