### PR TITLE
Fix type conv error when converting idx 2 dim list

### LINKED ISSUE #243: Potential integer overflow inside helper function idx_to_dim_list()
PIO2 restricts each element of gdimlen array to a 32-bit integer, but the total size (product of all elements) can still be a very large number that requires a 64-bit integer. Therefore, PIO_Offset type (64-bit integer) is used to store a 1-D index.

The helper function below (used a lot by box rearranger) converts a 1-D index into a coordinate value in an arbitrary dimension space. E.g., for index 4 into a array defined as a[3][2], will return 2,0.

```
inline void idx_to_dim_list(int ndims, const int *gdimlen, PIO_Offset idx,
                     PIO_Offset *dim_list)
{
    ...
    for (int i = ndims - 1; i >= 0; --i)
    {
        int next_idx;

        ...
        next_idx = idx / gdimlen[i];
        dim_list[i] = idx - (next_idx * gdimlen[i]);
        ...
    }
}
```
The above code doesn't look right, next_idx is int and idx is PIO_Offset: potential integer overflow will occur when "idx / gdimlen[i]" is larger than 2,147,483,647 (maximum 32-bit signed integer).

This bug has been confirmed: developers working on machine Summit have reported integer overflow when writing mpas fields (NCAR PIO issue 1583).

Only tests with large dimension lengths can reproduce this overflow issue (unfortunately, existing PIO unit tests use small lengths).

The following PIO example can invoke the overflow on workstation compute001 (it requires more than 35 GiB memory during run time due to large dimension lengths being used).
```
#include <stdio.h>
#include <mpi.h>
#include <pio.h>
#ifdef TIMING
#include <gptl.h>
#endif

#define NDIM 3
#define X_DIM_LEN 40000L
#define Y_DIM_LEN 60000L
#define Z_DIM_LEN 2L

int main(int argc, char* argv[])
{
  int my_rank;
  int ntasks;
  int niotasks;
  int ioproc_stride = 1;
  int ioproc_start = 0;
  PIO_Offset elements_per_pe;
  int dim_len[NDIM] = {X_DIM_LEN, Y_DIM_LEN, Z_DIM_LEN};
  int iosysid;
  int ioid;
  PIO_Offset *compdof = NULL;

#ifdef TIMING    
  GPTLinitialize();
#endif   

  MPI_Init(&argc, &argv);
  MPI_Comm_rank(MPI_COMM_WORLD, &my_rank);
  MPI_Comm_size(MPI_COMM_WORLD, &ntasks);

  niotasks = ntasks; 
  PIOc_Init_Intracomm(MPI_COMM_WORLD, niotasks, ioproc_stride, ioproc_start, PIO_REARR_BOX, &iosysid);

  elements_per_pe = X_DIM_LEN * Y_DIM_LEN * Z_DIM_LEN / ntasks;
  compdof = malloc(elements_per_pe * sizeof(PIO_Offset));
  
  for (int i = 0; i < elements_per_pe; i++)
    compdof[i] = my_rank * elements_per_pe + i + 1;
    
  PIOc_InitDecomp(iosysid, PIO_INT, NDIM, dim_len, (PIO_Offset)elements_per_pe, compdof, &ioid, NULL, NULL, NULL);

  free(compdof);

  PIOc_freedecomp(iosysid, ioid);

  PIOc_finalize(iosysid);

  MPI_Finalize();

#ifdef TIMING    
  GPTLfinalize();
#endif 

  return 0;
}
```
When we run this example with 16 MPI tasks on compute001, we can obtain the following output by printing out some debug information inside  idx_to_dim_list():
```
[rank = 14] idx = 4294967296, gdimlen[2] = 2, next_idx = -2147483648, expected value = 2147483648
[rank = 15] idx = 4500000000, gdimlen[2] = 2, next_idx = -2044967296, expected value = 2250000000
```

### PR DESCRIPTION
**Pull request by jayeshkrishna**
Fixing type conversion error when converting a 1d index to
multi-dim index.

Fixes #243

### CODE REVIEW

**Comment by PeterCaldwell** [comment]
Hi Jayesh - is this the bug preventing SCORPIO use at ne512 and ne1024? If so, do you have a timeline for getting it into E3SM master? Thanks!

**Comment by jayeshkrishna** [comment]
Yes, this fix is required to run ne512 simulations with Scorpio.
I am right now trying out ne1024 simulations on Cori and debugging issues with it. I was hoping this fix might also work with ne1024 simulations, but it looks like we might need some more fixes to get the ne1024 cases working.
I am going to work on a fix for ne1024 simulations tomorrow and if I can't get that working in a day or two I will create a separate patch release with this fix (or if I can get the ne1024 case working, will release a patch containing all the required fixes). So in couple of days I will have a PR with this fix to merge to E3SM master.

**Comment by ndkeen** [comment]
Can you point me to a casedir where you have tried PIO_VERSION=2 with ne512?

**Comment by PeterCaldwell** [comment]
Great, thanks Jayesh! Like Noel says, it would be great if we could look at your ne512 case. I'm particularly curious whether you're writing restarts, which we've been having problems with. Also, it might be useful to let me, Noel, and @brhillman know if/what kind of issues you run into with ne1024 in case we've seen them before (in the case that they're not actually PIO2 problems).

**Comment by jayeshkrishna** [comment]
I have started updating a confluence page (https://acme-climate.atlassian.net/wiki/spaces/EPG/pages/1041499237/I+O+Performance+of+E3SM+High+Resolution+Simulations+BEING+UPDATED) with information on how to run the ne512 simulations. The confluence page should now contain the script that I used to configure/build and run E3SM. 
To run the ne512 simulation with the latest version of scorpio,

**Comment by jayeshkrishna** [comment]
Regarding issues with ne1024 runs, they seem to be limitations in PnetCDF (due to limitations in the underlying MPI I/O library) due to the large size of the variables written out. We should be able to circumvent this in Scorpio.

**Comment by rljacob** [comment]
I thought CDF5 format allows any size variable?

**Comment by jayeshkrishna** [comment]
Yes, the CDF5 format allows writing out large variables but this issue is related to the size of data written out from a single process.

**Pull request merged**
